Docs: Add missing tablenames for Group and Role
Using your example I received the following error
qlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship User.roles - there are no foreign keys linking these tables via secondary table 'user_role'.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify 'primaryjoin' and 'secondaryjoin' expressions.

Adding a tablename as on sqlalchemy website solves this problem
https://docs.sqlalchemy.org/en/13/orm/basic_relationships.html#many-to-many